[package]
name = "random_num"
version = "0.1.0"
authors = ["jasdeep"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
magic-num = { git = "https://github.com/cfilipescu/magic-num.git", branch = "main"}